/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nova.pasta.app;

import nova.pasta.list.LinkedList;

import static nova.pasta.utilities.StringUtils.join;
import static nova.pasta.utilities.StringUtils.split;
import static nova.pasta.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
